window.APP_ENV = {
  SUPABASE_URL: "__SUPABASE_URL__",
  SUPABASE_ANON_KEY: "__SUPABASE_ANON_KEY__",
  SILICONFLOW_API_KEY: "__SILICONFLOW_API_KEY__",
  VOLCENGINE_API_KEY: "__VOLCENGINE_API_KEY__",
  XAI_API_KEY: "__XAI_API_KEY__"
};